theme: jekyll-theme-minimal
title: G00GEO - Geoprocessamento
description: Website com dados da disciplina de Geoprocessamento do Departamento de Engenharia de Transportes (DET) do Centro Federal de Educação Tecnológica de Minas Gerais
